In [1]:
import pandas as pd

In [16]:
print("Structured Data")
df_excel=pd.read_excel(r"Students.xlsx")
df_excel

Structured Data

   Student ID  Student Name Course  Semester  GPA Enrollment Date
0         101  Rahul Sharma    MCA         1  8.5      2026-08-16
1         102   Priya Patel    MCA         1  9.2      2026-08-16
2         103    Amit Verma  BTech         3  7.8      2025-08-12
3         104   Sneha Reddy    MCA         1  8.9      2026-08-18
4         105  Vikram Singh  BTech         5  6.4      2024-08-10

In [17]:
print("Structured Data")
df_csv=pd.read_csv(r"Students.csv")
df_csv

Structured Data

   Student ID  Student Name Course  Semester  GPA Enrollment Date
0         101  Rahul Sharma    MCA         1  8.5      16-08-2026
1         102   Priya Patel    MCA         1  9.2      16-08-2026
2         103    Amit Verma  BTech         3  7.8      12-08-2025
3         104   Sneha Reddy    MCA         1  8.9      18-08-2026
4         105  Vikram Singh  BTech         5  6.4      10-08-2024

In [15]:
print(" Unstructured Data:")
df_txt=pd.read_csv(r"data.txt")
df_txt

 Unstructured Data:

Empty DataFrame
Columns: [Hey team,  just checking in on the MCA student records. Rahul Sharma (ID: 101) is doing really well in his MCA course,  currently sitting at an 8.5 GPA. He mentioned he knows Python and Java. Also,  Priya Patel (ID: 102) is top of the class with a 9.2 GPA. She is focusing heavily on Data Science,  R,  and SQL. Drop her an email at priya@email.com if you need her project files. Let's update the database whenever we get a chance. Thanks!]
Index: []

In [18]:
print("Semi-Structured Data")
df_json=pd.read_json(r"student.json")
df_json

Semi-Structured Data

,id,name,course,gpa,skills,contact
0,101,Rahul Sharma,MCA,8.5,"[Python, Java]","{'email': 'rahul@email.com', 'phone': '9876543..."
1,102,Priya Patel,MCA,9.2,"[Data Science, R, SQL]",{'email': 'priya@email.com'}